In [2]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
print(a)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


In [5]:
a.max()

23

In [7]:
a.mean()

3.0

In [8]:
len(a)

12

In [7]:
pos = a > 0
a[pos]
len(a[pos])

5

In [8]:
neg = a < 0
a[neg]
len(a[neg])

4

In [23]:
even =(a % 2 == 0) & (a > 0)
even
a[even]

array([ 4, 10, 12])

In [24]:
odd = (a % 2 == 1) & (a > 0)
odd
a[odd]

array([23,  3])

In [25]:
b = (a + 3) 
b[pos]
len(b[pos])

5

In [10]:
b = (a + 3) 
b[neg]
len(b[neg])

4

In [12]:
sq = a **2
sq

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [27]:
sq.mean()

74.0

In [15]:
std = np.std(sq)
std

144.0243035046516

In [18]:
mean = np.mean(a)
mean

3.0

In [32]:
centering = a -(a.mean())
centering
centering.mean()

0.0

In [89]:
z_score = [(z-mean)/dev for z in a]
z_score

[-1.8922203176304273,
 -1.8111392365493462,
 -1.7841122095223192,
 -1.6354635608736705,
 -1.9733013987115082,
 -1.9597878851979949,
 -1.9462743716844813,
 -1.9462743716844813,
 -1.9462743716844813,
 -2.0273554527655624,
 -1.9057338311439407,
 -2.040868966279076]